<a href="https://colab.research.google.com/github/srimaailuri/Machine_learning/blob/master/KFold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt

In [ ]:
digits=load_digits()

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [ ]:
lr=LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9611111111111111

In [ ]:
LogisticRegression?

In [ ]:
svm=SVC(gamma='auto')
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.39814814814814814

In [ ]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9629629629629629

In [ ]:
?SVC

In [ ]:
rf?

In [ ]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [24]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [25]:
def get_score(model,x_train,y_train,x_test,y_test):
  model.fit(x_train,y_train)
  return model.score(x_test,y_test)

In [34]:
from sklearn.model_selection import StratifiedKFold
fold=StratifiedKFold(n_splits=3)

scores_logistic=[]
scores_SVC=[]
scores_RF=[]

for train_index,test_index in kf.split(digits.data,digits.target):
  x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
  scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'),x_train,y_train,x_test,y_test))
  scores_SVC.append(get_score(SVC(),x_train,y_train,x_test,y_test))
  scores_RF.append(get_score(RandomForestClassifier(n_estimators=20),x_train,y_train,x_test,y_test))


multi_class='ovr'
ovr = one vs rest
ex: ['apple','bat','cat']
*   'apple' vs ['bat','cat']
*   'bat' vs ['apple','cat']
*   'cat' vs ['apple','bat']

multi_class='ovo'
ovo -- one vs one

ex: ['apple','bat','cat']
*   'apple' vs 'bat'
*   'apple' vs 'cat'
*  'bat' vs 'cat'
*  'bat' vs 'apple'
*   'cat' vs 'apple'
*   'cat' vs 'bat'

In [35]:
scores_logistic

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [36]:
scores_SVC

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [37]:
scores_RF

[0.9048414023372288, 0.9565943238731218, 0.9265442404006677]

In [38]:
from sklearn.model_selection import cross_val_score

In [39]:
scores1=cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target,cv=10)
np.average(scores1)

0.8837026691495966

you can play around with parameters to obtain high accuracy